### ISSUE TITLE
another issue 

### ISSUE THREAD

**Issue by haskellstudio** [chzihan/A596#2]
for example: 
in racket:
  ` (* 3 (let/cc k1 ( k1 (* 7 (let/cc k ( k 5))))))`
will evaluate to 105.         because first  contiuation is  (lambda(x) (* 7 x)) and then apply another contiuation  which is  (lambda(x) (* 3 x)).
  
`(* 3 (let/cc k1 ( k1 (* 7 (let/cc k ( k1 5))))))`
will evaluate to 15.  because contiuation is  (lambda(x) (* 3 x))
    
in the assignment , we can rewrite the code to add throw before k.

```
(value-of-cps (lex `(* 3 (let/cc k1 (throw k1 (* 7 (let/cc k (throw k 5)))))) `())
              (empty-env)
              (empty-k))
```
should evaluate to 105.

```
(value-of-cps (lex `(* 3 (let/cc k1 (throw k1 (* 7 (let/cc k (throw k1 5)))))) `())
              (empty-env)
              (empty-k))
```
should evaluate to 15.

but according your code , both the two case evaluate to 105, i guess 
https://github.com/chzihan/A596/blob/540c84705687320668c6720eca5c34146cecabab/Homework/HW7/a7_05.rkt#L38 this line, the` (cons k acc)` should appear in ['(let/cc ,k ,e) (let ([v (lex e acc)]) '(letcc ,v))]

**Comment by chzihan** [comment]
Yes, you are definitely right!!!
That two line should be:
```
      [`(let/cc ,k ,e)   (let ([v (lex e (cons k acc))]) `(letcc ,v))]
      [`(throw ,k ,e)   `(throw ,(lex k acc) ,(lex e acc))]
```
Since we assume all our input is valid, so the parameter of throw should get bounded outside (where there is a let/cc) rather than in the current scope.
Thanks for your comment and now I've fixed it.

**Comment by haskellstudio** [comment]
ok~ 
is there anyway I can get B621  "https://cgi.soic.indiana.edu/~c311/doku.php?id=b621"  assignment  material?   I want to learn this course next few weeks.   
It doesn't matter if there is no such material~

**Comment by chzihan** [comment]
Hi, I think this course hasn't provided for a while but Dan still provide some advanced PL courses.
Recently, he is working with his new book [little typer](http://thelittletyper.com/) and gives lectures about dependent type. I think for the previous year he taught the stuff in l

**Comment by haskellstudio** [comment]
ok~  Got it .
Looking forward to The Little Typer~
